name: Receive the data

on:
  workflow_dispatch:
    inputs:
      version:
        description: version of app
        default: 1.10.0
        required: true

  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{ steps.Export.outputs.version }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "version"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/version.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip version.zip

      - name: 'Export'
        run: |
          version=`cat ./version`
          echo $version
          echo "::set-output name=version::$(cat ./version)"

  echo-input:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo ${{ github.event.inputs.version }}

  echo-download:
    runs-on: ubuntu-latest
    needs: [download]
    steps:
      - run: echo ${{ needs.download.outputs.version }}