name: Sentry Release & Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@1.2.0
        with:
          version: latest
          token: ${{ SECRETS.SENTRY_TOKEN }} # from GitHub secrets
          organization: samvelian
          project: personal-website
      - name: Get tag name
        run: |
          tag_name=${{ github.ref_name }}
          echo "tag_version=${tag_name//v}" >> $GITHUB_ENV
      - name: Start release
        run: sentry-cli releases new ${{ env.tag_version }}
      # - name: Sync commits
      #   run: sentry-cli releases set-commits --auto ${{ env.tag_version }}
      - name: Finalise release
        run: sentry-cli releases finalize ${{ env.tag_version }}
      - name: Deploy
        run: sentry-cli releases deploys ${{ env.tag_version }} new -e production
